package bg.wandersnap.enumeration;

public enum AuthorityEnum {
    READ_PRIVILEGE,
    WRITE_PRIVILEGE,
    UPDATE_PRIVILEGE,
    DELETE_PRIVILEGE,
    UPLOAD_PRIVILEGE,
    VIEW_PROFILE_PRIVILEGE,
    USER_MANAGEMENT_PRIVILEGE,
    ROLE_MANAGEMENT_PRIVILEGE,
    RESOURCE_MANAGEMENT_PRIVILEGE,
    SYSTEM_CONFIGURATION_PRIVILEGE
}